### ISSUE TITLE
Failed: No provider for AngularFireAuth!

### ISSUE THREAD

**Issue by mayuba** [iglewski/Annotator#3]
Le test ne trouve pas d'où provient AngularFireAuth.

```
Chrome 62.0.3202 (Windows 7 0.0.0) AppComponent should create the app FAILED
        Failed: No provider for AngularFireAuth!
        Error: No provider for AngularFireAuth!
            at injectionError C:/xampp/htdocs/INF1583-Annotator/node_modules/@angular/core/@angular/core.es5.js:1169:22)
            at noProviderError C:/xampp/htdocs/INF1583-Annotator/node_modules/@angular/core/@angular/core.es5.js:1207:1)
            at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.
js.ReflectiveInjector_._throwOrNull C:/xampp/htdocs/INF1583-Annotator/node_modules/@angular/core/@angular/core.es5.js:2649:1)
            at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.
js.ReflectiveInjector_._getByKeyDefault C:/xampp/htdocs/INF1583-Annotator/node_modules/@angular/core/@angular/core.es5.js:2688:1)
            at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.
js.ReflectiveInjector_._getByKey C:/xampp/htdocs/INF1583-Annotator/node_modules/@angular/core/@angular/core.es5.js:2620:1)
            at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.
js.ReflectiveInjector_.get C:/xampp/htdocs/INF1583-Annotator/node_modules/@angular/core/@angular/core.es5.js:2489:1)
            at resolveNgModuleDep C:/xampp/htdocs/INF1583-Annotator/node_modules/@angular/core/@angular/core.es5.js:9492:1)
            at NgModuleRef_.webpackJsonp.../../../core/@angular/core.es5.js.NgModuleRef_.get C:/xampp/htdocs/INF1583-Annotator/node_modules/@angular/core/@angular/core.es5.js:10562:1)
            at resolveDep C:/xampp/htdocs/INF1583-Annotator/node_modules/@angular/core/@angular/core.es5.js:11050:1)
            at createClass C:/xampp/htdocs/INF1583-Annotator/node_modules/@angular/core/@angular/core.es5.js:10914:1)
Chrome 62.0.3202 (Windows 7 0.0.0): Executed 1 of 3 (1 FAILED) (0 secs / 0.108 secs)
```

**Comment by mayuba** [comment]
Le problème se trouve dans le fichier [app.component.spec.ts](https://github.com/iglewski/Annotator/blob/master/src/app/app.component.spec.ts)
Le module [app.module.ts](https://github.com/iglewski/Annotator/blob/master/src/app/app.module.ts) importe AngularFireAuth mais le fichier [app.component.spec.ts](https://github.com/iglewski/Annotator/blob/master/src/app/app.component.spec.ts) n'importe pas le module utiliser par l'application pour le test.

donc il faut ajouter dans beforeEach à la line 4 de [app.component.spec.ts](https://github.com/iglewski/Annotator/blob/master/src/app/app.component.spec.ts), le module d'authentification AngularFireAuthModule ainsi que les autres module firebase utilisé dans application comme AngularFireDatabaseModule et AngularFireModule.
il faut aussi initialisé le module
```
describe('AppComponent', () => { 
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      imports: [
        AngularFireModule.initializeApp(firebaseConfig), //ajout
        AngularFireAuthModule, //ajout
        AngularFireDatabaseModule //ajout
      ],
    }).compileComponents();

  })); 
```

Ajouter l'importation des modules dans le fichier [app.component.spec.ts](https://github.com/iglewski/Annotator/blob/master/src/app/app.component.spec.ts) :
```
import { FirebaseApp, FirebaseAppConfig, AngularFireModule } from 'angularfire2';
import { AngularFireAuth, AngularFireAuthModule } from 'angularfire2/auth';
import { AngularFireDatabaseModule } from 'angularfire2/database';
import * as firebase from 'firebase/app';
import { firebaseConfig } from './app.module';
```
le deux test ci-bas ne devrait pas être asynchrone car il n ya pas de changement après compilation
[app.component.spec.ts](https://github.com/iglewski/Annotator/blob/master/src/app/app.component.spec.ts): line 11-20  
```
it('should create the app', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  }));

 it(`should have as title 'app'`, async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app.title).toEqual('app');
  }));
```
on devrait comparer title s'il est Annotator comme défini dans [app.component.ts](https://github.com/iglewski/Annotator/blob/master/src/app/app.component.ts) : line 14.
`title = 'Annotateur';`
doit être remplacer par 👍 
```
it('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  });

  it(`should have as title 'Annotateur'`, () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app.title).toEqual('Annotateur');
  });
```
voir le lien de changement 
https://github.com/mayuba/Annotator/commit/7e9a1fbd1d8f2e8b0a87e525c87ea0aba98b5c9c

**Comment by mayuba** [comment]
![screen shot 2017-11-13 at 4 50 24 pm](https://user-images.githubusercontent.com/6999749/32751219-0cb4d420-c893-11e7-825f-dc1cbc6345b0.png)
